### ISSUE TITLE
Parameter name mismatch between FGDiff.svg and index.html

### ISSUE THREAD

**Issue by zivanfi** [eBay/FGrav#34]
Hi,

First of all, thanks a lot for this truly great visualization tool. The diff view is incredibly useful but I found that it only works with preprocessed files that already contains two measurements. When trying to diff two files that contain a single measurement each, I ran into the following problems:

- The html file puts the file names into the parameters `first` and `second` but the code in `FGDiff.svg` expects them in the parameters `1st` and `2nd`. This can be easily fixed by changing the parameter names in `index.html`.
- ~~The frames of the displayed graph are entirely white and not colored according to the difference (unlike when displaying a diff from a single file of two measurements). When hovering over the frames, it display information about both data points, so the data is there, it just not visualized for some reason, but I could not figure out why.~~

Thanks,

Zoltan

**Comment by zivanfi** [comment]
Ah, sorry, when taking a closer look at the displayed numbers I noticed that they are indentical, which made me recognize that I accidentally specified the same file for both parameters, so there was no difference to show. Apologies for spamming you with this report, I would not have reported it for minor issue of the parameter names alone.

**Comment by langera** [comment]
No problem :) 
Good to know its being used.
